apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
  labels:
    app: gitops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      - name: sync
        image: alpine/git:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            git clone https://github.com/tu-usuario/tu-repositorio /tmp/html || (cd /tmp/html && git pull);
            cp -r /tmp/html/index.html /usr/share/nginx/html/index.html;
            sleep 30;
          done
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        emptyDir: {}
