name: Update ConfigMap
on:
  push:
    branches:
      - main

jobs:
  update-configmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.31.0'

      - name: Authenticate with Kubernetes
        run: |
          mkdir -p ~/.minikube/profiles/minikube ~/.kube
          echo "$CA_CRT_BASE64" | base64 -d > ~/.minikube/ca.crt
          echo "$CLIENT_CRT_BASE64" | base64 -d > ~/.minikube/profiles/minikube/client.crt
          echo "$CLIENT_KEY_BASE64" | base64 -d > ~/.minikube/profiles/minikube/client.key
          kubectl config set-cluster minikube --server=https://127.0.0.1:8443 --certificate-authority=~/.minikube/ca.crt
          kubectl config set-credentials minikube --client-certificate=~/.minikube/profiles/minikube/client.crt --client-key=~/.minikube/profiles/minikube/client.key
          kubectl config set-context minikube --cluster=minikube --user=minikube --namespace=default
          kubectl config use-context minikube

      - name: Update ConfigMap in Kubernetes
        run: |
          kubectl create configmap app-html \
          --from-file=app/index.html \
          --dry-run=client -o yaml | kubectl apply -f -
